/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-library-conventions")
}

dependencies {
    api(project(":list"))
    implementation("org.apache.ivy:ivy:2.5.1")
}
