name: Build

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v0
      with:
        dependency-graph: generate-and-submit
    - name: Build with Gradle
      run: ./gradlew build
